sudo: false

addons:
   apt:
     packages:
        - python-numpy 
        - python-scipy 
        - python-matplotlib 
        - python-sympy
        - python-tk
        - python-tables 
        - python-tornado
    

language: python
python: 2.7

 
virtualenv:
   system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=Brian     # Python script runs with Brian; should be just Python, but Brian engine is quick to set up...

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
    # install pyelectro
    - pip install git+https://github.com/NeuralEnsemble/pyelectro.git

    - pip install pyNeuroML
    - git clone https://github.com/NeuroML/NeuroMLlite.git
    - cd NeuroMLlite
    - python setup.py install
    - cd examples
    - python Example2.py # test one example...
    - cd ../..

script:
    - omv all -V
    
    
    
    

